config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  get '/my_lyrs' => "song_texts#user_song_texts", :as => :user_root
  
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end
  
  resources :song_texts, concerns: :paginatable

  get "/my_lyrs", to: "song_texts#user_song_texts", as:"user_song_texts"

  get "/profile/:id/", to: "pages#profile", as: "profile"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song_text.rb
class SongText < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :song_texts
  has_one_attached :avatar, dependent: :destroy
  has_one_attached :bkg_pic, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [ :username, :first_name, :last_name, :avatar, :bkg_pic])

  end
  # https://stackoverflow.com/questions/27177068/devise-user-model-not-updating
  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  
  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[ home profile ]

  def home
  end

  def profile
    @user = User.find(params[:id])
    @song_texts = []
    @user_song_texts = SongText.where(user: @user)
    @user_song_texts.each do |s|
      @song_texts << s if s.public_lyric == true
    end
  end
end

app/controllers/song_texts_controller.rb
class SongTextsController < ApplicationController
  before_action :set_song_text, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index profile ]

  def index
    @song_texts = policy_scope(SongText.where(public_lyric: true)).order(created_at: :desc).page params[:page]
    #@song_texts = @all_song_texts.where(public_lyric: true)
  end

  def user_song_texts
    set_page_to_redirect
    @user = current_user
    @song_text = current_user.song_texts.new
    @song_texts = SongText.where(user_id: @user)
    authorize @song_texts
  end

  def show
    @user = current_user
    @song_text = SongText.find(params[:id])
  end

  def new
    @song_text = current_user.song_texts.new
    authorize @song_text
  end

  def edit
  end

  def create
    @song_text = current_user.song_texts.new(song_text_params)
    authorize @song_text
    if @song_text.save
      flash[:notice] = " \n #{@song_text.title} was created"
    else
      flash[:notice] = " \n #{@song_text.title} was NOT created: #{@song_text.errors}"
    end
    redirect_to user_song_texts_path(song: @song_text.id)
  end

  def update
    @song_text.update(song_text_params)
    authorize @song_text
    if @song_text.save
      flash[:notice] = " \n #{@song_text.title} was edited"
    else
      flash[:notice] = " \n #{@song_text.title} was NOT edited: #{@song_text.errors}"
    end
    redirect_to user_song_texts_path(song: @song_text.id)
  end

  def destroy

    @song_text.user = current_user
    if @song_text.destroy
      flash[:notice] = " \n #{@song_text.title} was deleted"
    else
      flash[:notice] = " \n #{@song_text.title} was NOT deleted: #{@song_text.errors}"
    end
    redirect_to user_song_texts_path
  end

  private

  def set_song_text
    @song_text = SongText.find(params[:id])
    authorize @song_text
  end

  def song_text_params
    params.require(:song_text).permit(:title, :content, :notes, :rating, :color_tag, :created_at, :updated_at)
  end

  def set_page_to_redirect
    session[:return_to] ||= request.referer
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Blinker:wght@200;300;400;600;800&family=Roboto&display=swap" rel="stylesheet">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="body-container">
      <%= render 'shared/flashes' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-bkg">
  <%= render "shared/navbar" %>
  <div class="banner">
    <div class="home-content">
      <div class="info-area">
        <div class="info">
          <h3>No more paper mess:</h3> 
          <h1>your lyrics now organized.</h1>
          <hr>
          <ul>
            <li>Use colors to express moods</li><br>
            <li>Give your lyrics some notes to remember details about which rythm, key or emotion you envisioned for the song. You can also use the notes to explain your creative process and organize yourself when making the song reality! </li><br>
            <li>Explore what other users are writing.</li><br>
          </ul>
          <br><br>
          <h5 class="home-neon"> soon: </h5><br>
          <ul>
            <li>Phone support</li>
            <li>Add friends</li>
            <li>Search for rhymes while writing</li>
            <li>Easier Color Picking</li>
          </ul>
        </div>
      </div>
      <div class="action">
        <div class="logo-img home-neon">
          <%= image_tag "tmp/Asset-3d.svg", class: "logo" %> <br>
        </div>
        <div class="btn-area">
          <%= link_to "Your Lyrics", user_song_texts_path, class:"btn-home" %> 
          <%= link_to "Explore", song_texts_path, class:"btn-home" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<!--GRID wrapper-->
<div class="grid-container">
  <!--GRID -  navbar (holds more link to user and MyLy (to public index)) -->
  <div class="user-navbar">
    <%= render "shared/navbar" %>
  </div>
  
  <!--GRID -  user-tab (flexbox)-->
  <div class="user-tab">
  
    <!--user info-->
      <div class="user-info" style="background: linear-gradient(0deg, rgba(0,0,0,0.4821564749385534) 1%, rgba(255,255,255,0) 100%),  url(<% if @user.bkg_pic.attached? %><%= @user.bkg_pic.service_url %>) <% else %> https://images.unsplash.com/photo-1515405295579-ba7b45403062?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80)<% end %>;">
      <div class="user-btn">
          <p><%= link_to  "add friend  (soon)",  "#" %>  </p>
          
        </div>
        
        <div class="avatar-pic">        
          <% if @user.avatar.attached? %>
            <%= image_tag @user.avatar %>
          <% else %>
            <%= image_tag  "blank_avatar_0.png" %>
          <% end %>
          

          <h5 class="username">
            <% if @user.username %> 
              <%= @user.username %>  
            <% else %>
              <%= @user.email %>
            <% end %>    
          </h5>
        </div>
      </div>

    <!--lyrics menu -->
      <div class="lyrics-menu">
        <div class="each-lyric">
          <ul class="lyrics-list nav  flex-column" id="lyricsTab" role="tablist">
            <% if @song_texts %>
              <% @song_texts.each do |song_text| %>
                <li class="nav-item">
                  <h5 class="nav-link song-link 
                  <%= 'active' if params[:song] == song_text.id %> <%= 'active-border' if song_text.color_tag != "" %>" 
                  
                  id="song-<%= song_text.id %>-tab" data-toggle="tab" href="#song-<%= song_text.id %>" role="tab" aria-controls="#song-<%= song_text.id %>" aria-selected="false" 
                  
                  <%  if song_text.color_tag != "" %> style="border-right: 6px solid  <%= song_text.color_tag %>;" <% else %>style="border-right: 6px solid transparent;"<% end %>>
                  <%= "#{song_text.title}" %>
                  
                  </h5>
                </li> 
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>

  </div>

  <!--GRID -  lyr-tab -->
    <div class="lyrics-tab empty-tab-bkg">
      <div class="tab-content" id="LyricsTabContent">
        <!--Default Tab -->
          <div class="tab-pane fade <%= 'active show' unless params[:song] %>">
              <div class="empty-tab">
                <%= image_tag "tmp/Asset-3d.svg", class: "logo" %> <br>
              </div>
          </div>
                
        <% if @song_texts %>
          <% @song_texts.each do |song_text| %>

          <!-- TABS -->
            <div class="tab-pane fade <%= 'active show' if ["#{song_text.id}"].include? params[:song] %>" id="song-<%= song_text.id %>"  role="tabpanel" aria-labelledby="song-<%= song_text.id %>-tab">

            <!--GRID wrapper-->
              <div class="tab-bkg">
                <div class="lyrics-grid-wrapper" style="background-color: <% if song_text.color_tag != "" %><%= song_text.color_tag  %><% else %> #463F3A <%end%>; opacity: 80%;">
                  <div class="title" style="background-color: <% if song_text.color_tag != "" %><%= song_text.color_tag %><% else %> #463F3A <%end%>; border-bottom: 8px solid <% if song_text.color_tag != "" %><%= song_text.color_tag %><% else %> #463F3A <%end%>;">
                    <div class="title-container">
                      <h1><%= song_text.title %></h1>
                      <% if song_text.rating %>
                        <p><%= "⭐" * song_text.rating  %></p>
                      <% end %>
                    </div>
                  </div>
                  
                  <!-- LYRICS -->
                    <div class="lyrics-wrapper" style="background-color: <% if song_text.color_tag != "" %><%= song_text.color_tag %><% else %> #463F3A <%end%>; border-bottom: 8px solid <% if song_text.color_tag != "" %><%= song_text.color_tag %><% else %> #463F3A <%end%>;">
                      
                      <div class="lyrics">
                        <p><%= song_text.content %></p>
                      </div>

                      <div class="notes">
                        <p><%= song_text.notes %></p>
                      </div>
                    </div>

                </div>
              
              </div>
            </div>
          <% end %>
        <% end %>
      
      </div>
    </div>

  <!--  - Footer-->
  <div class="footer">

  </div>
<%#= raise %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= simple_form_for(@song_text) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="page-navbar">
      <!--Dropdown-->
        <div class="dropdown show">
          <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag("tmp/Asset-3d.svg")%>
          </a>

          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            
            <%= link_to "Home", root_path, class:"dropdown-item"  %>
            <%= link_to "Explore", song_texts_path, class:"dropdown-item"  %>
            <%= link_to "Your Lyrics", user_song_texts_path, class:"dropdown-item"  %>
            <%= link_to "About Us", "#", class:"dropdown-item"  %>
          </div>
        </div>
        
  <div class="nav-navbar">
      <ul class="home-nav-list">
        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "signup", new_user_registration_path %></li>
          <li><%= link_to "login", user_session_path %></li>
          <% end %>
      </ul>
  </div>
</div>

app/views/song_texts/edit.html.erb
<h1>Editing Song Text</h1>

<%= render 'form', song_text: @song_text %>

<%= link_to 'Show', @song_text %> |
<%= link_to 'Back', song_texts_path %>

app/views/song_texts/index.html.erb
<div class="index-bkg">
  <div class="index-grid-container">
    <div class="user-navbar">
      <%= render "shared/navbar" %>
    </div>
    <div class="index-content">
      <table>
        <tr>
          <th> </th>
          <th>Title</th>
          <th>Author</th>
          <th></th>
          
        </tr>
        <% @song_texts.each do |song_text| %>
        <!-- TABLE -->
          <tr>
            <td style="background-color: <% if song_text.color_tag != "" %> <%= song_text.color_tag %><% else %> #463F3A <%end%>;">
              
            </td>
            <td class="table-title" id="title-<%= song_text.id %>">
              <p><%= link_to song_text.title, profile_path(song_text.user.id, song: song_text.id ) %></p>
            </td>
            <td>
              
              <p><%= link_to (song_text.user.username if song_text.user.username)  || (song_text.user.email if song_text.user.email), profile_path(song_text.user.id, song: song_text.id ) %></p>
            </td>
            <td class="table-ratings">
              <p>
                <% if song_text.ratable == true %>
                  <%= "⭐" * song_text.rating %>
                <% else %>
                  not ratable
                <% end %>
              </p>
            </td>
        <% end %>
          </tr>
      </table>
      <div class="pag">
        <%= paginate @song_texts %>
      </div>
    </div>
    <div class="index-footer">
    </div>
  </div>
</div>

app/views/song_texts/new.html.erb
<div class="container main-container">
  <div class="content-container new-form-container">
    <h1>New Song Text</h1>

    <%= render 'form', song_text: @song_text %>

    <%= link_to 'Back', song_texts_path %>
  
  </div>
</div>

app/views/song_texts/show.html.erb
<div class="container" style="min-height: 100vh; background-color: #463F3A;">
  <%= link_to 'Back', song_texts_path %>
  <div class="title container" style="background-color: white; border: 5px solid <%= @song_text.color_tag if  @song_text.color_tag != "" %>;">
    <h1><%= @song_text.title %></h1>
    <div class="container">
      <div class="" style="background-color: white; text-align: center;
      white-space: pre-line;">
      by <%= @song_text.user.username %><br>
      email:<%= @song_text.user.email %><br><br>
        <%= @song_text.content %><br>
        <h1>notes</h1>
        <%= @song_text.notes %><br>
      </div>
    </div>
  </div>
  
</div>

app/views/song_texts/user_song_texts.html.erb
<!--GRID wrapper-->
<div class="grid-container">
  <!-- new lyric Modal -->
    <div class="modal fade" id="newLyricsModal" tabindex="-1" role="dialog" aria-labelledby="newLyricsModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="newLyricsModalLabel">New Lyrics</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= simple_form_for(@song_text) do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

            <div class="form-inputs">
              <%= f.input :title %>
              <%= f.input :content %>
              <%= f.input :notes %>
              <%= f.input :color_tag,  hint: 'Use HEX'%>
              <%= f.input :ratable ,  hint: 'Mark it if you want people to rate your song', label: "Ratable" %>
              <%= f.input :public_lyric, hint: 'Unmark it if you want to make it private', label: "Public"  %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.button :submit, 'Submit', class: "btn-submit" %>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  
  

  <!--GRID -  navbar (holds more link to user and MyLy (to public index)) -->
  <div class="user-navbar">
    <%= render "shared/navbar" %>
  </div>
  
  <!--GRID -  user-tab (flexbox)-->
  <div class="user-tab">
  
    <!--user info-->
      <div class="user-info" style="background: linear-gradient(0deg, rgba(0,0,0,0.4821564749385534) 1%, rgba(255,255,255,0) 100%),  url(<% if @user.bkg_pic.attached? %><%= @user.bkg_pic.service_url %>) <% else %> https://images.unsplash.com/photo-1515405295579-ba7b45403062?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80)<% end %>;">
        <div class="user-btn">
          <p><%= link_to  "profile",  edit_user_registration_path %>  </p>
          <p data-toggle="modal" data-target="#newLyricsModal" ><a>new</a></p>
        </div>
        
        <div class="avatar-pic">        
          <% if @user.avatar.attached? %>
            <%= image_tag @user.avatar %>
          <% else %>
            <%= image_tag  "blank_avatar_0.png" %>
          <% end %>
          

          <h5 class="username">
            <% if @user.username %> 
              <%= @user.username %>  
            <% else %>
              <%= @user.email %>
            <% end %>    
          </h5>
        </div>
      </div>

    <!--lyrics menu -->
      <div class="lyrics-menu">
        <div class="each-lyric">
          <ul class="lyrics-list nav  flex-column" id="lyricsTab" role="tablist">
            <% if @song_texts %>
              <% @song_texts.each do |song_text| %>
                <li class="nav-item">
                  <%= button_to "X" , song_text_path(song_text) , method: :delete , class:"delete-song", data: { confirm: "#{song_text.title} \n Are you sure you want to delete this song?"} %>
                  <h5 class="nav-link song-link 
                  <%= 'active' if ["#{song_text.id}"].include? params[:song] %> <%= 'active-border' if song_text.color_tag != "" %>" 
                  
                  id="song-<%= song_text.id %>-tab" data-toggle="tab" href="#song-<%= song_text.id %>" role="tab" aria-controls="#song-<%= song_text.id %>" aria-selected="false" 
                  
                  <%  if song_text.color_tag != "" %> style="border-right: 6px solid  <%= song_text.color_tag %>;" <% else %>style="border-right: 6px solid transparent;"<% end %>>
                  <%= "#{song_text.title}" %>
                  <%#= raise %>
                  </h5>
                </li> 
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>

  </div>

  <!--GRID -  lyr-tab -->
    <div class="lyrics-tab empty-tab-bkg">
      <div class="tab-content" id="LyricsTabContent">
        <!--Default Tab -->
          <div class="tab-pane fade <%= 'active show' unless params[:song] %>">
              <div class="empty-tab">
                <%= image_tag "tmp/Asset-3d.svg", class: "logo" %> <br>
              </div>
          </div>
                
        <% if @song_texts %>
          <% @song_texts.each do |song_text| %>

            <!-- Edit lyric Modal -->
              <div class="modal fade" id="editLyricsModal-<%= song_text.id %>" tabindex="-1" role="dialog" aria-labelledby="editLyricsModalLabel-<%= song_text.id %>" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="editLyricsModalLabel-<%= song_text.id %>"><%= song_text.title %></h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <%= simple_form_for(song_text) do |f| %>
                      <%= f.error_notification %>
                      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

                      <div class="form-inputs">
                        <%= f.input :title %>
                        <%= f.input :content %>
                        <%= f.input :notes %>
                        <%= f.input :color_tag,  hint: 'Use HEX'%>
                        <%= f.input :ratable ,  hint: 'Mark it if you want people to rate your song', label: "Ratable" %>
                        <%= f.input :public_lyric, hint: 'Unmark it if you want to make it private', label: "Public"  %>
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <%= f.button :submit, "Update", class: "btn-submit" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>


          <!-- TABS -->
            <div class="tab-pane fade <%= 'active show' if ["#{song_text.id}"].include? params[:song] %>" id="song-<%= song_text.id %>"  role="tabpanel" aria-labelledby="song-<%= song_text.id %>-tab">

            <!--GRID wrapper-->
              <div class="tab-bkg">
                <div class="lyrics-grid-wrapper" style="background-color: <% if song_text.color_tag != "" %><%= song_text.color_tag  %><% else %> #463F3A <%end%>; opacity: 80%;">
                  <div class="title" style="background-color: <% if song_text.color_tag != "" %><%= song_text.color_tag %><% else %> #463F3A <%end%>; border-bottom: 8px solid <% if song_text.color_tag != "" %><%= song_text.color_tag %><% else %> #463F3A <%end%>;">
                    <div class="title-container">
                      <h1><%= song_text.title %></h1>
                      <% if song_text.rating %>
                        <p><%= "⭐" * song_text.rating  %></p>
                      <% end %>
                    </div>
                  </div>
                  
                  <!-- LYRICS -->
                    <div class="lyrics-wrapper" style="background-color: <% if song_text.color_tag != "" %><%= song_text.color_tag %><% else %> #463F3A <%end%>; border-bottom: 8px solid <% if song_text.color_tag != "" %><%= song_text.color_tag %><% else %> #463F3A <%end%>;">
                      
                      <div class="lyrics">
                        <p><%= song_text.content %></p>
                      </div>

                      <div class="notes">
                        <p><%= song_text.notes %></p>
                      </div>
                    </div>
                    <%#= link_to "Edit", edit_song_text_path(song_text) %>
                    <h2 class="edit-song"><a href="/song_texts/edit" data-toggle="modal" data-target="#editLyricsModal-<%= song_text.id %>" style="color: <% if song_text.color_tag != "" %><%= song_text.color_tag %><% else %> #463F3A <%end%>;  background-color: <% if song_text.color_tag != "" %><%= song_text.color_tag %><% else %> #463F3A <%end%>;">Edit</a></h2>
                </div>
              
              </div>
            </div>
          <% end %>
        <% end %>
      
      </div>
    </div>

  <!--  - Footer-->
  <div class="footer">

  </div>

</div>